Database
IMY772-2022/via-web pull request #49
Opened 2022-05-14 05:51 UTC by ksamson2

Adding base changes needed for gql and changes needed for gitignore to fix amplify continuity errors

2022-05-17 18:04 UTC, christoff-linde requested changes

2022-05-17 18:04 UTC, christoff-linde commented on .gitignore
> +#amplify-do-not-edit-end
We should add `.DS_Store` to the `.gitignore`

2022-05-17 18:04 UTC, christoff-linde commented on amplify/backend/api/viaweb/cli-inputs.json
> +    "gqlSchemaPath": "/Users/camsamso/Documents/Personal/UP/IMY 772/temp/via-web/amplify/backend/api/viaweb/schema.graphql",
would this absolute path not cause issues? can we update it to be a relative one

2022-05-17 18:05 UTC, ksamson2 commented on amplify/backend/api/viaweb/cli-inputs.json
> +    "gqlSchemaPath": "/Users/camsamso/Documents/Personal/UP/IMY 772/temp/via-web/amplify/backend/api/viaweb/schema.graphql",
good point.. it's an auto-generated file though so not sure how changing it works, I can take a look

2022-05-19 17:13 UTC, ksamson2 commented on amplify/backend/api/viaweb/cli-inputs.json
> +    "gqlSchemaPath": "/Users/camsamso/Documents/Personal/UP/IMY 772/temp/via-web/amplify/backend/api/viaweb/schema.graphql",
Not sure why this is still committing :/ I added it to the gitignore. It should be a file created by amplify

2022-05-22 06:46 UTC, christoff-linde approved these changes

2022-05-23 14:30 UTC, merged