update: added confirmation modal to items in album
IMY772-2022/via-web pull request #85
Opened 2022-06-20 16:54 UTC by brian-david

There is a lot of css customisation on the other components, so I needed to use !important in a lot of places to get around the other styling, especially for buttons

2022-06-20 17:56 UTC, ksamson2 requested changes
I like the overall look, I think the buttons are a bit too big and the modal is a bit squashed. Either later tonight or early tomorrow, Nicole and I should merge in new updates to the album page. This moves the delete button to the edit page. Sorry for conflict, but could you update your PR after that is merged in so that this happens on the edit page then and not on the album screen?

2022-06-20 17:56 UTC, ksamson2 commented on src/components/Album/Item.tsx
> +    setConfirmModalOpen(false)
If it's set to false by default, why do we need this line?

2022-06-20 17:56 UTC, ksamson2 commented on src/components/ConfirmModal/confirmModal.scss
> +button.is-normal :hover {
On my end, this style doesn't take effect so the text is white and not visible

2022-06-20 18:00 UTC, ksamson2 commented
I think sync with Christoff because I know he fixed getting around using the !important recently. Could we not maybe attach a class to the button so that we aren't relying on our or even bulma's default styles for the button?

2022-06-21 05:17 UTC, brian-david commented
> I like the overall look, I think the buttons are a bit too big and the modal is a bit squashed. Either later tonight or early tomorrow, Nicole and I should merge in new updates to the album page. This moves the delete button to the edit page. Sorry for conflict, but could you update your PR after that is merged in so that this happens on the edit page then and not on the album screen?

2022-06-21 05:18 UTC, brian-david commented
> I like the overall look, I think the buttons are a bit too big and the modal is a bit squashed. Either later tonight or early tomorrow, Nicole and I should merge in new updates to the album page. This moves the delete button to the edit page. Sorry for conflict, but could you update your PR after that is merged in so that this happens on the edit page then and not on the album screen?

yip, I'll check in tonight and update

2022-06-21 18:16 UTC, brian-david commented
> > I like the overall look, I think the buttons are a bit too big and the modal is a bit squashed. Either later tonight or early tomorrow, Nicole and I should merge in new updates to the album page. This moves the delete button to the edit page. Sorry for conflict, but could you update your PR after that is merged in so that this happens on the edit page then and not on the album screen?

I expanded the modal a bit. I thought it made sense to have big button as we're going for old blind(ish) people. But I can make them smaller

2022-06-21 18:21 UTC, brian-david commented
Oh and there shouldn't (touch wood) be any merge conflicts now if you pull into dev

2022-06-21 21:03 UTC, christoff-linde approved these changes

2022-06-21 21:03 UTC, merged